CREATE TABLE public.cinemas (
    id integer NOT NULL,
    name character varying NOT NULL,
    logo_url character varying,
    location character varying NOT NULL,
    city_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

ALTER TABLE public.cinemas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cinemas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cinemas
    ADD CONSTRAINT cinemas_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cinemas
    ADD CONSTRAINT cinemas_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE CASCADE;