CREATE TABLE public.seats (
    id integer NOT NULL,
    cinema_id integer NOT NULL,
    row_letter character varying NOT NULL,
    seat_number integer NOT NULL,
    seat_type character varying DEFAULT 'regular'::character varying,
    created_at timestamp without time zone DEFAULT now()
);

ALTER TABLE public.seats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_cinema_id_fkey FOREIGN KEY (cinema_id) REFERENCES public.cinemas(id) ON DELETE CASCADE;