CREATE TABLE public.orders (
    id integer NOT NULL,
    user_id integer NOT NULL,
    schedule_id integer NOT NULL,
    total_price numeric NOT NULL,
    payment_status character varying DEFAULT 'pending'::character varying,
    booking_code character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_booking_code_key UNIQUE (booking_code);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;