INSERT INTO "movies" ("title", "synopsis", "duration", "release_date", "director_id", "poster_url", "backdrop_url", "popularity_score") VALUES
('The Last Frontier', 'A gripping tale of survival in the harsh wilderness of Alaska, where a group of explorers must face nature''s fury and their own demons.', 148, '2025-11-15', 1, 'https://image.tmdb.org/t/p/w500/poster1.jpg', 'https://image.tmdb.org/t/p/original/backdrop1.jpg', 8.5),
('Echoes of Tomorrow', 'In a dystopian future, a scientist discovers a way to communicate with the past, but changing history comes with devastating consequences.', 136, '2025-12-20', 6, 'https://image.tmdb.org/t/p/w500/poster2.jpg', 'https://image.tmdb.org/t/p/original/backdrop2.jpg', 9.2),
('Midnight in Paris Revisited', 'A romantic comedy about a writer who finds himself transported to 1920s Paris every midnight, meeting his literary heroes.', 112, '2025-10-05', 7, 'https://image.tmdb.org/t/p/w500/poster3.jpg', 'https://image.tmdb.org/t/p/original/backdrop3.jpg', 7.8),
('The Silent Witness', 'A psychological thriller where a deaf woman becomes the only witness to a brutal crime and must outsmart the killer to survive.', 125, '2025-09-18', 8, 'https://image.tmdb.org/t/p/w500/poster4.jpg', 'https://image.tmdb.org/t/p/original/backdrop4.jpg', 8.1),
('Quantum Paradox', 'When quantum physicists accidentally open a portal to parallel universes, they must prevent a catastrophic collision of realities.', 155, '2026-03-15', 1, 'https://image.tmdb.org/t/p/w500/poster5.jpg', 'https://image.tmdb.org/t/p/original/backdrop5.jpg', 9.5),
('Ocean''s Legacy', 'The next generation of Ocean''s crew pulls off the most ambitious heist in history - stealing a priceless artifact from the bottom of the sea.', 142, '2026-05-22', 2, 'https://image.tmdb.org/t/p/w500/poster6.jpg', 'https://image.tmdb.org/t/p/original/backdrop6.jpg', 8.9),
('The Forgotten Kingdom', 'An epic fantasy adventure where a young warrior must unite the seven kingdoms to defeat an ancient evil rising from the shadows.', 168, '2026-07-10', 5, 'https://image.tmdb.org/t/p/w500/poster7.jpg', 'https://image.tmdb.org/t/p/original/backdrop7.jpg', 9.3),
('Neon Dreams', 'In a cyberpunk metropolis, a hacker uncovers a conspiracy that could enslave humanity through advanced AI technology.', 138, '2026-08-28', 6, 'https://image.tmdb.org/t/p/w500/poster8.jpg', 'https://image.tmdb.org/t/p/original/backdrop8.jpg', 8.7),
('Love in the Time of AI', 'A heartwarming romantic comedy about a woman who falls in love with an AI, questioning what it means to be human.', 118, '2026-10-14', 7, 'https://image.tmdb.org/t/p/w500/poster9.jpg', 'https://image.tmdb.org/t/p/original/backdrop9.jpg', 7.5),
('The Final Symphony', 'A biographical drama about a legendary composer''s final masterpiece and the personal sacrifices behind musical genius.', 145, '2026-12-25', 10, 'https://image.tmdb.org/t/p/w500/poster10.jpg', 'https://image.tmdb.org/t/p/original/backdrop10.jpg', 8.4);
